// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCvrV3BSqcEytsWbnqV4allulFBJnkg-I',
    appId: '1:1029239756284:web:7f52beb37609e177fbce79',
    messagingSenderId: '1029239756284',
    projectId: 'fruit-hub-35380',
    authDomain: 'fruit-hub-35380.firebaseapp.com',
    storageBucket: 'fruit-hub-35380.firebasestorage.app',
    measurementId: 'G-EBFQM6YDCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXdIzzMBnX1hWAgoqGsBIjJucJml0kYII',
    appId: '1:1029239756284:android:7bfaee0de21d3d75fbce79',
    messagingSenderId: '1029239756284',
    projectId: 'fruit-hub-35380',
    storageBucket: 'fruit-hub-35380.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCvrV3BSqcEytsWbnqV4allulFBJnkg-I',
    appId: '1:1029239756284:web:8609bdf4db9fd383fbce79',
    messagingSenderId: '1029239756284',
    projectId: 'fruit-hub-35380',
    authDomain: 'fruit-hub-35380.firebaseapp.com',
    storageBucket: 'fruit-hub-35380.firebasestorage.app',
    measurementId: 'G-E26JYBQZ1T',
  );
}
