// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCJnea7g4LkMjnUGQ9dMI8P7tzKyjknOg',
    appId: '1:755128532494:web:665964a6abb791eaef465f',
    messagingSenderId: '755128532494',
    projectId: 'fruits-app-d1e70',
    authDomain: 'fruits-app-d1e70.firebaseapp.com',
    storageBucket: 'fruits-app-d1e70.firebasestorage.app',
    measurementId: 'G-4FT6R92311',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkr9-q5GxX8IUT9CjByMpY9XlQ2m_Y1lk',
    appId: '1:755128532494:android:c943ea9a3c52b715ef465f',
    messagingSenderId: '755128532494',
    projectId: 'fruits-app-d1e70',
    storageBucket: 'fruits-app-d1e70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkGeiUIcynjBSBHzSNjbp5x8pHuMqZ-X4',
    appId: '1:755128532494:ios:6d217461b2b42a39ef465f',
    messagingSenderId: '755128532494',
    projectId: 'fruits-app-d1e70',
    storageBucket: 'fruits-app-d1e70.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkGeiUIcynjBSBHzSNjbp5x8pHuMqZ-X4',
    appId: '1:755128532494:ios:6d217461b2b42a39ef465f',
    messagingSenderId: '755128532494',
    projectId: 'fruits-app-d1e70',
    storageBucket: 'fruits-app-d1e70.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCJnea7g4LkMjnUGQ9dMI8P7tzKyjknOg',
    appId: '1:755128532494:web:7fbf77100e4e8c43ef465f',
    messagingSenderId: '755128532494',
    projectId: 'fruits-app-d1e70',
    authDomain: 'fruits-app-d1e70.firebaseapp.com',
    storageBucket: 'fruits-app-d1e70.firebasestorage.app',
    measurementId: 'G-JD851D25BT',
  );
}
