// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBv9rHAgPchsC7hPWfUJ3JMi9qTCNRuzg',
    appId: '1:912313250490:web:12c669db5bacaa1d37c883',
    messagingSenderId: '912313250490',
    projectId: 'fruit-hub-5a97b',
    authDomain: 'fruit-hub-5a97b.firebaseapp.com',
    storageBucket: 'fruit-hub-5a97b.firebasestorage.app',
    measurementId: 'G-231T781GFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyJoFCOMOXBvcsJjiOQZju4hMpElueS7c',
    appId: '1:912313250490:android:21f01e4fcf3c47d137c883',
    messagingSenderId: '912313250490',
    projectId: 'fruit-hub-5a97b',
    storageBucket: 'fruit-hub-5a97b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBv9rHAgPchsC7hPWfUJ3JMi9qTCNRuzg',
    appId: '1:912313250490:web:cbc2ed5e64bd5bb937c883',
    messagingSenderId: '912313250490',
    projectId: 'fruit-hub-5a97b',
    authDomain: 'fruit-hub-5a97b.firebaseapp.com',
    storageBucket: 'fruit-hub-5a97b.firebasestorage.app',
    measurementId: 'G-X1GLRRXFVW',
  );
}
